### ISSUE TITLE
timeout while executing a shell script

### ISSUE THREAD

**Issue by jcasteels** [jjmartres/VIMbix#22]
I get in zabbix a timeout on every item. 
vimbix-client["-u","http://{$VIMBIX_ADDRESS}:{$VIMBIX_PORT}/{HOST.IP}/datastores"]] became not supported: timeout while executing a shell script

I changed the time-out setting in zabbix_server.conf to the maximum and still having the same errors.

log from vimbox:
I, [2013-10-15T10:23:38.155496 #19757]  INFO -- : xx.xx.xx.xx: connected
I, [2013-10-15T10:23:38.164014 #19757]  INFO -- : xx.xx.xx.xx: data collection started
I, [2013-10-15T10:25:01.657893 #19757]  INFO -- : xx.xx.xx.xx: data collection ended (83 seconds)

**Comment by pycode122** [comment]
I'm facing the same problem...could you tell me Ip settings in which file..??
